sudo: required
language: node_js
addons:
  apt:
    # needed for cypress https://github.com/cypress-io/cypress/issues/1526
    packages:
      - libgconf-2-4
node_js:
  - "10"
cache:
  bundler: false
  yarn: true
  directories:
    - .build-cache
    - ~/.cache
git:
  submodules: false
before_install: git fetch origin master
install: yarn install --frozen-lockfile --non-interactive --audit --silent

jobs:
  include:
    - stage: test
      name: "Unit tests and code checks"
      script:
        - yarn format:check
        - yarn lint
        - yarn test
    - stage: test
      name: "E2E tests"
      script: yarn e2e:ci
    - stage: build
      language: bash
      name: "Build the docker image"
      node_js:
      services:
        - docker
      install: skip
      script: RELEASE_VERSION=latest ./make-web.sh --build-ml
      after_success: |
        if [ "${TRAVIS_BRANCH}" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
          echo 'Master banch build detected, pushing to docker hub'
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker tag flogo/flogo-web:latest flogo/flogo-web:unstable
          docker push flogo/flogo-web:unstable
          docker tag flogo/flogo-web:latest-ml flogo/flogo-web:unstable-ml
          docker push flogo/flogo-web:unstable-ml
        fi

        if [ ! -z "$TRAVIS_TAG" ]; then
          echo "Tag detected, pushing tag '${TRAVIS_TAG}' to docker hub"
          docker tag flogo/flogo-web:latest "flogo/flogo-web:${TRAVIS_TAG}"
          docker push "flogo/flogo-web:${TRAVIS_TAG}"
        fi
